/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping
         * @description 检查服务可用性
         */
        get: operations["ping_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a short video */
        post: operations["create_video_api_v1_videos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subtitle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate subtitle only */
        post: operations["create_subtitle_api_v1_subtitle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate audio only */
        post: operations["create_audio_api_v1_audio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all tasks */
        get: operations["get_all_tasks_api_v1_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query task status */
        get: operations["get_task_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        /** Delete a generated short video task */
        delete: operations["delete_video_api_v1_tasks__task_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/musics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve local BGM files */
        get: operations["get_bgm_list_api_v1_musics_get"];
        put?: never;
        /**
         * Upload a background music file
         * @description Validate an MP3, M4A, AAC, WAV, FLAC, OGG, OPUS, or WMA file up to 30 MB and store it under an immutable UUID filename in storage/bgm.
         */
        post: operations["upload_bgm_file_api_v1_musics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/video_materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve local video materials */
        get: operations["get_video_materials_list_api_v1_video_materials_get"];
        put?: never;
        /** Upload the video material file to the local videos directory */
        post: operations["upload_video_material_file_api_v1_video_materials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stream/{file_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Video */
        get: operations["stream_video_api_v1_stream__file_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/download/{file_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Video
         * @description download video
         *     :param request: Request request
         *     :param file_path: video file path, eg: /cd1727ed-3473-42a2-a7da-4faafafec72b/final-1.mp4
         *     :return: video file
         */
        get: operations["download_video_api_v1_download__file_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scripts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a script for the video */
        post: operations["generate_video_script_api_v1_scripts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate video terms based on the video script */
        post: operations["generate_video_terms_api_v1_terms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social-metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate social publishing metadata */
        post: operations["generate_video_social_metadata_api_v1_social_metadata_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: operations["get_projects_api_v1_projects_get"];
        put?: never;
        /** Create a project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List episodes */
        get: operations["get_episodes_api_v1_episodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episodes/{episode_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one episode */
        get: operations["get_episode_api_v1_episodes__episode_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Move an episode to another project */
        patch: operations["update_episode_api_v1_episodes__episode_id__patch"];
        trace?: never;
    };
    "/api/v1/episodes/{episode_id}/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List an episode's scenes */
        get: operations["get_scenes_api_v1_episodes__episode_id__scenes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episodes/{episode_id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List an episode's source materials */
        get: operations["get_assets_api_v1_episodes__episode_id__assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episodes/{episode_id}/renders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List an episode's finished videos */
        get: operations["get_renders_api_v1_episodes__episode_id__renders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a task's captured logs
         * @description Logs are an in-memory ring buffer in the process that ran the task
         *     (`app/services/task_logs.py`), capped at the 20 most recent tasks. A task
         *     started in a different process -- the Streamlit page, say -- has no logs
         *     here, and neither does one whose buffer has since been evicted. Both cases
         *     return an empty list rather than a 404.
         */
        get: operations["get_task_logs_api_v1_tasks__task_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssetData */
        AssetData: {
            /**
             * Kind
             * @default material
             */
            kind: string;
            /** File Name */
            file_name: string;
            /**
             * Provider
             * @default
             */
            provider: string;
            /**
             * Search Term
             * @default
             */
            search_term: string;
            /** Duration S */
            duration_s?: number | null;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
        };
        /** AssetListData */
        AssetListData: {
            /** Assets */
            assets: components["schemas"]["AssetData"][];
        };
        /** AssetListResponse */
        AssetListResponse: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /**
             * Message
             * @default success
             */
            message: string | null;
            data: components["schemas"]["AssetListData"];
        };
        /** AudioRequest */
        AudioRequest: {
            /** Video Script */
            video_script: string;
            /**
             * Video Language
             * @default
             */
            video_language: string | null;
            /**
             * Voice Name
             * @default zh-CN-XiaoxiaoNeural-Female
             */
            voice_name: string | null;
            /**
             * Voice Volume
             * @default 1
             */
            voice_volume: number | null;
            /**
             * Voice Rate
             * @default 1.2
             */
            voice_rate: number | null;
            /**
             * Bgm Type
             * @default random
             */
            bgm_type: string | null;
            /**
             * Bgm File
             * @default
             */
            bgm_file: string | null;
            /**
             * Bgm Volume
             * @default 0.2
             */
            bgm_volume: number | null;
            /**
             * Video Source
             * @default local
             */
            video_source: string | null;
        };
        /** BgmRetrieveData */
        BgmRetrieveData: {
            /** Files */
            files: components["schemas"]["FileData"][];
        };
        /**
         * BgmRetrieveResponse
         * @example {
         *       "data": {
         *         "files": [
         *           {
         *             "file": "4fca18fce7344f3aa824777a40d45c8c.mp3",
         *             "name": "4fca18fce7344f3aa824777a40d45c8c.mp3",
         *             "size": 1891269
         *           }
         *         ]
         *       },
         *       "message": "success",
         *       "status": 200
         *     }
         */
        BgmRetrieveResponse: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /**
             * Message
             * @default success
             */
            message: string | null;
            data: components["schemas"]["BgmRetrieveData"];
        };
        /** BgmUploadData */
        BgmUploadData: {
            /** File */
            file: string;
        };
        /**
         * BgmUploadResponse
         * @example {
         *       "data": {
         *         "file": "4fca18fce7344f3aa824777a40d45c8c.mp3"
         *       },
         *       "message": "success",
         *       "status": 200
         *     }
         */
        BgmUploadResponse: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /**
             * Message
             * @default success
             */
            message: string | null;
            data: components["schemas"]["BgmUploadData"];
        };
        /** Body_upload_bgm_file_api_v1_musics_post */
        Body_upload_bgm_file_api_v1_musics_post: {
            /** File */
            file: string;
        };
        /** Body_upload_video_material_file_api_v1_video_materials_post */
        Body_upload_video_material_file_api_v1_video_materials_post: {
            /** File */
            file: string;
        };
        /** EpisodeDetailData */
        EpisodeDetailData: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: number;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Topic
             * @default
             */
            topic: string;
            /**
             * Script
             * @default
             */
            script: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown;
            };
            /**
             * Run Data
             * @default {}
             */
            run_data: {
                [key: string]: unknown;
            };
            /** State */
            state?: number | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
        } & {
            [key: string]: unknown;
        };
        /** EpisodeDetailResponse */
        EpisodeDetailResponse: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /**
             * Message
             * @default success
             */
            message: string | null;
            data: components["schemas"]["EpisodeDetailData"];
        };
        /** EpisodeListData */
        EpisodeListData: {
            /** Episodes */
            episodes: components["schemas"]["EpisodeSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** EpisodeListResponse */
        EpisodeListResponse: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /**
             * Message
             * @default success
             */
            message: string | null;
            data: components["schemas"]["EpisodeListData"];
        };
        /**
         * EpisodeSummary
         * @description 列表行。与 WebUI 任务面板使用的字段一致，只是路径换成了 URL。
         */
        EpisodeSummary: {
            /** Task Id */
            task_id: string;
            /** Subject */
            subject: string;
            /** State */
            state?: number | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Mtime */
            mtime: number;
            /**
             * Video Url
             * @default
             */
            video_url: string;
            /**
             * Has Restore Data
             * @default false
             */
            has_restore_data: boolean;
            /** Cross Post State */
            cross_post_state?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /** EpisodeUpdateRequest */
        EpisodeUpdateRequest: {
            /** Project Id */
            project_id: number;
        };
        /** EpisodeUpdateResponse */
        EpisodeUpdateResponse: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /**
             * Message
             * @default success
             */
            message: string | null;
            /** Data */
            data?: null;
        };
        /** FileData */
        FileData: {
            /** Name */
            name: string;
            /** Size */
            size: number;
            /** File */
            file: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MaterialInfo */
        MaterialInfo: {
            /**
             * Provider
             * @default pexels
             */
            provider: string;
            /**
             * Url
             * @default
             */
            url: string;
            /**
             * Duration
             * @default 0
             */
            duration: number;
            /** Source Info */
            source_info?: {
                [key: string]: unknown;
            } | null;
        };
        /** ProjectCreateRequest */
        ProjectCreateRequest: {
            /** Name */
            name: string;
        };
        /** ProjectCreateResponse */
        ProjectCreateResponse: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /**
             * Message
             * @default success
             */
            message: string | null;
            data: components["schemas"]["ProjectData"];
        };
        /** ProjectData */
        ProjectData: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Episodes
             * @default 0
             */
            episodes: number;
        };
        /** ProjectListData */
        ProjectListData: {
            /** Projects */
            projects: components["schemas"]["ProjectData"][];
        };
        /** ProjectListResponse */
        ProjectListResponse: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /**
             * Message
             * @default success
             */
            message: string | null;
            data: components["schemas"]["ProjectListData"];
        };
        /** RenderData */
        RenderData: {
            /** File Name */
            file_name: string;
            /** Url */
            url: string;
            /** Size Bytes */
            size_bytes?: number | null;
        };
        /** RenderListData */
        RenderListData: {
            /** Renders */
            renders: components["schemas"]["RenderData"][];
        };
        /** RenderListResponse */
        RenderListResponse: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /**
             * Message
             * @default success
             */
            message: string | null;
            data: components["schemas"]["RenderListData"];
        };
        /** SceneData */
        SceneData: {
            /** Idx */
            idx: number;
            /**
             * Narration
             * @default
             */
            narration: string;
            /**
             * Search Term
             * @default
             */
            search_term: string;
            /** Start Ms */
            start_ms?: number | null;
            /** End Ms */
            end_ms?: number | null;
        };
        /** SceneListData */
        SceneListData: {
            /** Scenes */
            scenes: components["schemas"]["SceneData"][];
        };
        /** SceneListResponse */
        SceneListResponse: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /**
             * Message
             * @default success
             */
            message: string | null;
            data: components["schemas"]["SceneListData"];
        };
        /** SubtitleRequest */
        SubtitleRequest: {
            /** Video Script */
            video_script: string;
            /**
             * Video Language
             * @default
             */
            video_language: string | null;
            /**
             * Voice Name
             * @default zh-CN-XiaoxiaoNeural-Female
             */
            voice_name: string | null;
            /**
             * Voice Volume
             * @default 1
             */
            voice_volume: number | null;
            /**
             * Voice Rate
             * @default 1.2
             */
            voice_rate: number | null;
            /**
             * Bgm Type
             * @default random
             */
            bgm_type: string | null;
            /**
             * Bgm File
             * @default
             */
            bgm_file: string | null;
            /**
             * Bgm Volume
             * @default 0.2
             */
            bgm_volume: number | null;
            /**
             * Subtitle Position
             * @default bottom
             */
            subtitle_position: string | null;
            /**
             * Subtitle Display Mode
             * @default sentence
             * @enum {string}
             */
            subtitle_display_mode: "sentence" | "word_by_word";
            /**
             * Subtitle Animation
             * @default none
             * @enum {string}
             */
            subtitle_animation: "none" | "pop_spring";
            /**
             * Font Name
             * @default STHeitiMedium.ttc
             */
            font_name: string | null;
            /**
             * Text Fore Color
             * @default #FFFFFF
             */
            text_fore_color: string | null;
            /**
             * Text Background Color
             * @default false
             */
            text_background_color: boolean | string;
            /**
             * Rounded Subtitle Background
             * @default false
             */
            rounded_subtitle_background: boolean;
            /**
             * Font Size
             * @default 60
             */
            font_size: number;
            /**
             * Stroke Color
             * @default #000000
             */
            stroke_color: string | null;
            /**
             * Stroke Width
             * @default 1.5
             */
            stroke_width: number;
            /**
             * Video Source
             * @default local
             */
            video_source: string | null;
            /**
             * Subtitle Enabled
             * @default true
             */
            subtitle_enabled: boolean | null;
        };
        /**
         * TaskDeletionResponse
         * @example {
         *       "message": "success",
         *       "status": 200
         *     }
         */
        TaskDeletionResponse: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /**
             * Message
             * @default success
             */
            message: string | null;
            /** Data */
            data?: null;
        };
        /**
         * TaskListData
         * @description 分页任务列表结构。
         */
        TaskListData: {
            /** Tasks */
            tasks: components["schemas"]["TaskStatusData"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * TaskListResponse
         * @description 任务列表使用独立响应模型，避免与单任务查询混用文档结构。
         * @example {
         *       "data": {
         *         "page": 1,
         *         "page_size": 10,
         *         "tasks": [
         *           {
         *             "progress": 50,
         *             "state": 4,
         *             "task_id": "6c85c8cc-a77a-42b9-bc30-947815aa0558"
         *           }
         *         ],
         *         "total": 1
         *       },
         *       "message": "success",
         *       "status": 200
         *     }
         */
        TaskListResponse: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /**
             * Message
             * @default success
             */
            message: string | null;
            data: components["schemas"]["TaskListData"];
        };
        /** TaskLogData */
        TaskLogData: {
            /** Task Id */
            task_id: string;
            /** Logs */
            logs: string[];
        };
        /** TaskLogResponse */
        TaskLogResponse: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /**
             * Message
             * @default success
             */
            message: string | null;
            data: components["schemas"]["TaskLogData"];
        };
        /**
         * TaskQueryResponse
         * @description 任务查询会返回生成状态和可选的跨平台发布状态。
         *
         *     生成失败时包含 `failed_stage` 和 `error`；生成完成后如果启用了自动发布，
         *     `cross_post_state` 会依次进入 pending、processing、complete 或 failed。
         * @example {
         *       "data": {
         *         "cross_post_results": [
         *           {
         *             "success": true
         *           }
         *         ],
         *         "cross_post_state": "complete",
         *         "progress": 100,
         *         "state": 1,
         *         "task_id": "6c85c8cc-a77a-42b9-bc30-947815aa0558",
         *         "videos": [
         *           "/tasks/example/final-1.mp4"
         *         ]
         *       },
         *       "message": "success",
         *       "status": 200
         *     }
         * @example {
         *       "data": {
         *         "error": "TTS request timed out",
         *         "failed_stage": "audio",
         *         "progress": 30,
         *         "state": -1,
         *         "task_id": "6c85c8cc-a77a-42b9-bc30-947815aa0558"
         *       },
         *       "message": "success",
         *       "status": 200
         *     }
         */
        TaskQueryResponse: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /**
             * Message
             * @default success
             */
            message: string | null;
            data: components["schemas"]["TaskStatusData"];
        };
        /**
         * TaskResponse
         * @example {
         *       "data": {
         *         "task_id": "6c85c8cc-a77a-42b9-bc30-947815aa0558"
         *       },
         *       "message": "success",
         *       "status": 200
         *     }
         */
        TaskResponse: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /**
             * Message
             * @default success
             */
            message: string | null;
            data: components["schemas"]["TaskResponseData"];
        };
        /** TaskResponseData */
        TaskResponseData: {
            /** Task Id */
            task_id: string;
        };
        /**
         * TaskStatusData
         * @description 任务查询对外保证的稳定字段；历史和扩展字段继续原样透传。
         */
        TaskStatusData: {
            /** Task Id */
            task_id: string;
            /** State */
            state?: number | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Videos */
            videos?: string[] | null;
            /** Combined Videos */
            combined_videos?: string[] | null;
            /** Failed Stage */
            failed_stage?: string | null;
            /** Error */
            error?: string | null;
            /** Cross Post State */
            cross_post_state?: ("pending" | "processing" | "complete" | "failed") | null;
            /** Cross Post Results */
            cross_post_results?: {
                [key: string]: unknown;
            }[] | null;
            /** Cross Post Error */
            cross_post_error?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** TaskVideoRequest */
        TaskVideoRequest: {
            /** Video Subject */
            video_subject: string;
            /**
             * Video Script
             * @default
             */
            video_script: string;
            /** Video Terms */
            video_terms?: string | unknown[] | null;
            /** @default 9:16 */
            video_aspect: components["schemas"]["VideoAspect"] | null;
            /** @default cover */
            video_fit_mode: components["schemas"]["VideoFitMode"];
            /** @default random */
            video_concat_mode: components["schemas"]["VideoConcatMode"] | null;
            video_transition_mode?: components["schemas"]["VideoTransitionMode"] | null;
            /**
             * Video Clip Duration
             * @default 5
             */
            video_clip_duration: number;
            /**
             * Video Clip Speed
             * @default 1
             */
            video_clip_speed: number | null;
            /**
             * Match Materials To Script
             * @default false
             */
            match_materials_to_script: boolean;
            /**
             * Video Count
             * @default 1
             */
            video_count: number;
            /**
             * Video Source
             * @default pexels
             */
            video_source: string | null;
            /** Video Materials */
            video_materials?: components["schemas"]["MaterialInfo"][] | null;
            /** Custom Audio File */
            custom_audio_file?: string | null;
            /**
             * Video Language
             * @default
             */
            video_language: string | null;
            /**
             * Voice Name
             * @default
             */
            voice_name: string | null;
            /**
             * Voice Volume
             * @default 1
             */
            voice_volume: number | null;
            /**
             * Voice Rate
             * @default 1
             */
            voice_rate: number | null;
            /**
             * Bgm Type
             * @default random
             */
            bgm_type: string | null;
            /**
             * Bgm File
             * @default
             */
            bgm_file: string | null;
            /**
             * Bgm Volume
             * @default 0.2
             */
            bgm_volume: number | null;
            /**
             * Video Music Prompt
             * @default
             */
            video_music_prompt: string;
            /**
             * Sonilo Bgm Prompt
             * @default
             */
            sonilo_bgm_prompt: string;
            /**
             * Subtitle Enabled
             * @default true
             */
            subtitle_enabled: boolean | null;
            /**
             * Subtitle Position
             * @default bottom
             */
            subtitle_position: string | null;
            /**
             * Subtitle Display Mode
             * @default sentence
             * @enum {string}
             */
            subtitle_display_mode: "sentence" | "word_by_word";
            /**
             * Subtitle Animation
             * @default none
             * @enum {string}
             */
            subtitle_animation: "none" | "pop_spring";
            /**
             * Custom Position
             * @default 70
             */
            custom_position: number;
            /**
             * Font Name
             * @default STHeitiMedium.ttc
             */
            font_name: string | null;
            /**
             * Text Fore Color
             * @default #FFFFFF
             */
            text_fore_color: string | null;
            /**
             * Text Background Color
             * @default false
             */
            text_background_color: boolean | string;
            /**
             * Rounded Subtitle Background
             * @default false
             */
            rounded_subtitle_background: boolean;
            /**
             * Font Size
             * @default 60
             */
            font_size: number;
            /**
             * Stroke Color
             * @default #000000
             */
            stroke_color: string | null;
            /**
             * Stroke Width
             * @default 1.5
             */
            stroke_width: number;
            /**
             * N Threads
             * @default 2
             */
            n_threads: number | null;
            /**
             * Paragraph Number
             * @default 1
             */
            paragraph_number: number;
            /**
             * Video Script Prompt
             * @default
             */
            video_script_prompt: string;
            /**
             * Custom System Prompt
             * @default
             */
            custom_system_prompt: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VideoAspect
         * @enum {string}
         */
        VideoAspect: "16:9" | "9:16" | "1:1";
        /**
         * VideoConcatMode
         * @enum {string}
         */
        VideoConcatMode: "random" | "sequential";
        /**
         * VideoFitMode
         * @description How source clips with a different aspect ratio fill the output canvas.
         * @enum {string}
         */
        VideoFitMode: "cover" | "contain";
        /** VideoMaterialRetrieveData */
        VideoMaterialRetrieveData: {
            /** Files */
            files: components["schemas"]["FileData"][];
        };
        /**
         * VideoMaterialRetrieveResponse
         * @example {
         *       "data": {
         *         "files": [
         *           {
         *             "file": "/MoneyPrinterTurbo/resource/videos/example.mp4",
         *             "name": "example.mp4",
         *             "size": 12345678
         *           }
         *         ]
         *       },
         *       "message": "success",
         *       "status": 200
         *     }
         */
        VideoMaterialRetrieveResponse: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /**
             * Message
             * @default success
             */
            message: string | null;
            data: components["schemas"]["VideoMaterialRetrieveData"];
        };
        /** VideoMaterialUploadData */
        VideoMaterialUploadData: {
            /** File */
            file: string;
        };
        /**
         * VideoMaterialUploadResponse
         * @example {
         *       "data": {
         *         "file": "/MoneyPrinterTurbo/resource/videos/example.mp4"
         *       },
         *       "message": "success",
         *       "status": 200
         *     }
         */
        VideoMaterialUploadResponse: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /**
             * Message
             * @default success
             */
            message: string | null;
            data: components["schemas"]["VideoMaterialUploadData"];
        };
        /** VideoScriptData */
        VideoScriptData: {
            /** Video Script */
            video_script: string;
        };
        /** VideoScriptRequest */
        VideoScriptRequest: {
            /**
             * Video Subject
             * @default 春天的花海
             */
            video_subject: string | null;
            /**
             * Video Language
             * @default
             */
            video_language: string | null;
            /**
             * Paragraph Number
             * @default 1
             */
            paragraph_number: number;
            /**
             * Video Script Prompt
             * @default
             */
            video_script_prompt: string;
            /**
             * Custom System Prompt
             * @default
             */
            custom_system_prompt: string;
        };
        /**
         * VideoScriptResponse
         * @example {
         *       "data": {
         *         "video_script": "春天的花海，是大自然的一幅美丽画卷。在这个季节里，大地复苏，万物生长，花朵争相绽放，形成了一片五彩斑斓的花海..."
         *       },
         *       "message": "success",
         *       "status": 200
         *     }
         */
        VideoScriptResponse: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /**
             * Message
             * @default success
             */
            message: string | null;
            data: components["schemas"]["VideoScriptData"];
        };
        /** VideoSocialMetadataData */
        VideoSocialMetadataData: {
            /** Title */
            title: string;
            /** Caption */
            caption: string;
            /** Hashtags */
            hashtags: string[];
        };
        /** VideoSocialMetadataRequest */
        VideoSocialMetadataRequest: {
            /**
             * Video Subject
             * @default A day in Shanghai
             */
            video_subject: string | null;
            /**
             * Video Script
             * @default
             */
            video_script: string | null;
            /**
             * Language
             * @default auto
             */
            language: string | null;
            /**
             * Platform
             * @default tiktok
             */
            platform: string | null;
        };
        /**
         * VideoSocialMetadataResponse
         * @example {
         *       "data": {
         *         "caption": "Save this quick Shanghai inspiration and follow for more short travel ideas.",
         *         "hashtags": [
         *           "#shorts",
         *           "#travel",
         *           "#shanghai",
         *           "#viral",
         *           "#fyp"
         *         ],
         *         "title": "A Day in Shanghai You Should Not Miss"
         *       },
         *       "message": "success",
         *       "status": 200
         *     }
         */
        VideoSocialMetadataResponse: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /**
             * Message
             * @default success
             */
            message: string | null;
            data: components["schemas"]["VideoSocialMetadataData"];
        };
        /** VideoTermsData */
        VideoTermsData: {
            /** Video Terms */
            video_terms: string[];
        };
        /** VideoTermsRequest */
        VideoTermsRequest: {
            /**
             * Video Subject
             * @default 春天的花海
             */
            video_subject: string | null;
            /**
             * Video Script
             * @default 春天的花海，如诗如画般展现在眼前。万物复苏的季节里，大地披上了一袭绚丽多彩的盛装。金黄的迎春、粉嫩的樱花、洁白的梨花、艳丽的郁金香……
             */
            video_script: string | null;
            /**
             * Amount
             * @default 5
             */
            amount: number | null;
            /**
             * Match Materials To Script
             * @default false
             */
            match_materials_to_script: boolean;
        };
        /**
         * VideoTermsResponse
         * @example {
         *       "data": {
         *         "video_terms": [
         *           "sky",
         *           "tree"
         *         ]
         *       },
         *       "message": "success",
         *       "status": 200
         *     }
         */
        VideoTermsResponse: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /**
             * Message
             * @default success
             */
            message: string | null;
            data: components["schemas"]["VideoTermsData"];
        };
        /**
         * VideoTransitionMode
         * @enum {string}
         */
        VideoTransitionMode: "None" | "Shuffle" | "FadeIn" | "FadeOut" | "SlideIn" | "SlideOut" | "ZoomIn" | "ZoomOut";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description pong */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    create_video_api_v1_videos_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskVideoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_subtitle_api_v1_subtitle_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubtitleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_audio_api_v1_audio_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AudioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_tasks_api_v1_tasks_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                /** @description Task ID */
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskQueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_video_api_v1_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                /** @description Task ID */
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDeletionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bgm_list_api_v1_musics_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BgmRetrieveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_bgm_file_api_v1_musics_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_bgm_file_api_v1_musics_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BgmUploadResponse"];
                };
            };
            /** @description The filename, format, size, or audio stream is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description FFmpeg validation or persistent storage is unavailable */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_video_materials_list_api_v1_video_materials_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoMaterialRetrieveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_video_material_file_api_v1_video_materials_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_video_material_file_api_v1_video_materials_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoMaterialUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_video_api_v1_stream__file_path__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                file_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_video_api_v1_download__file_path__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                file_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_video_script_api_v1_scripts_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VideoScriptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoScriptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_video_terms_api_v1_terms_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VideoTermsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoTermsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_video_social_metadata_api_v1_social_metadata_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VideoSocialMetadataRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoSocialMetadataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_episodes_api_v1_episodes_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                project_id?: number | null;
                query?: string;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_episode_api_v1_episodes__episode_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                /** @description Episode / task ID */
                episode_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_episode_api_v1_episodes__episode_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                /** @description Episode / task ID */
                episode_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EpisodeUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenes_api_v1_episodes__episode_id__scenes_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                /** @description Episode / task ID */
                episode_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assets_api_v1_episodes__episode_id__assets_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                /** @description Episode / task ID */
                episode_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_renders_api_v1_episodes__episode_id__renders_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                /** @description Episode / task ID */
                episode_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_logs_api_v1_tasks__task_id__logs_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                /** @description Task ID */
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
